### ISSUE TITLE
Soundboard is showing under mixer instead of next to it

### ISSUE THREAD

**Issue by Scaby79** [CDeenen/Soundscape#34]
Using the soundboard module with the game system "Das Schwarze Auge" (German; the english version ic called "the dark eye"), the soundbord is not showing next to the mixer as intended but under it instead:

![image](https://github.com/CDeenen/Soundscape/assets/25106826/153572ba-9b70-41a7-9a4c-b7529312db51)

It makes it much more difficult to handle it.

Maybe there is an easy fix possilbe in the css?

Would appreciate it very much.

Thx in advance!

**Comment by CDeenen** [comment]
At first glance I think it's because the system changes the core Foundry styling for common elements. This probably makes either the mixer or soundboard section too wide. I remember I was having some difficulties with it, but I should probably have it automatically set the width of the soundscape window instead of hardcoding it. I'll see what I can do.

**Comment by Scaby79** [comment]
The problem was fixed in the css of the game system! 😉
