### ISSUE TITLE
Doesn't work in v11

### ISSUE THREAD

**Issue by eupatorus** [CDeenen/Soundscape#37]
1.1.1 update doesn't seem to function in v11, afaik. There's no button for it in the Playlists menu as in the past anyway. If it moved I can't find it. I tried launch with only Soundscape module running and still nothing.

**Comment by CDeenen** [comment]
I can't reproduce this, could you try reinstalling the module?
If that doesn't help, what exact Foundry version are you on (e.g. v11.303) and what gaming system and version?
When you open the console (press F12, check that you're in the console tab) do you get any errors when you refresh? And what happens when you type `game.soundscape.mixerApp.render(true)` in the bottom of the console?

**Comment by eupatorus** [comment]
Ah yes, this corrected it! Thanks!

It defaults to "Gamemaster" (which I am, and afaik was sufficient in past versions) but I changed it to match my user name within Foundry ("DungeonMaster") and it works now.

Appreciate the response and the excellent mod!

**Comment by eupatorus** [comment]
Ah yes, this corrected it! Thanks!

It defaults to "Gamemaster" (which I am, and afaik was sufficient in past versions) but I changed it to match my user name within Foundry ("DungeonMaster") and it works now.

**Comment by CDeenen** [comment]
Happy to hear that!
I created an issue (#38) to autodetect the target player and configure it correctly when the module is first launched. This will hopefully prevent this from occuring in the future.
