### ISSUE TITLE
[BUG] Cannot open soundboard configuration dialog

### ISSUE THREAD

**Issue by Stendarpaval** [CDeenen/Soundscape#7]
**Setup**
 - OS: MacOS (though Foundry runs on a Raspberry Pi 4 running Rasbian (Linux))
 - Browser: Chrome
 - Module version: 1.0.1
 - Foundry version: 0.8.8
 - Gaming system & version: dnd5e 1.3.6
 - Any other modules enabled: no

**Describe the bug**
When I click on the name of a sound on the soundboard, no configuration dialog shows up and instead an error is displayed in the console.

**Screenshots**
Screenshot of the sound name I clicked:

<img width="870" alt="soundscape-bug-screenshot-2" src="https://user-images.githubusercontent.com/17188192/125592569-6cbc0385-97ea-4b81-bc2e-12d6d426846b.png">

**Console Log**
Screenshot of the console error:

<img width="690" alt="soundscape-bug-screenshot-1" src="https://user-images.githubusercontent.com/17188192/125593139-3a833cb7-463c-4653-90c7-7ab3fd3437bf.png">

**Additional context**
No other modules enabled. I only used sounds from the SoundFx module. The problem seems to lie in locating the template.

P.S. I love all the effort that has obviously gone into this module. Great fan, thanks for making this module!

(Edit: uploaded wrong console error screenshot, fixed it now)

**Comment by CDeenen** [comment]
Thank for opening this issue. I noticed after uploading that Foundry didn't capitalize the folder name of the module, while I did have mine capitalized in my development build, so Foundry couldn't find the files. I uploaded a fix, but apparently forgot to fix it for the soundboard config, oops :).
It should be fixed in the new version (v1.0.2) that's available now.

**Comment by Stendarpaval** [comment]
Can confirm that it works for me now, thank you!
